<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="18633" started-at="2019-10-22T12:27:36 IST" finished-at="2019-10-22T12:27:55 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="18633" started-at="2019-10-22T12:27:36 IST" finished-at="2019-10-22T12:27:55 IST">
      <class name="scripts.Scenario31">
        <test-method status="PASS" signature="selectDriver()[pri:0, instance:scripts.Scenario31@6973bf95]" name="selectDriver" is-config="true" duration-ms="13325" started-at="2019-10-22T12:27:36 IST" finished-at="2019-10-22T12:27:50 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectDriver -->
        <test-method status="FAIL" signature="execute31()[pri:0, instance:scripts.Scenario31@6973bf95]" name="execute31" duration-ms="3969" started-at="2019-10-22T12:27:50 IST" finished-at="2019-10-22T12:27:54 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.fail(Assert.java:102)
at scripts.Scenario31.execute31(Scenario31.java:44)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- execute31 -->
        <test-method status="PASS" signature="closeDriver()[pri:0, instance:scripts.Scenario31@6973bf95]" name="closeDriver" is-config="true" duration-ms="1163" started-at="2019-10-22T12:27:54 IST" finished-at="2019-10-22T12:27:55 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
      </class> <!-- scripts.Scenario31 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
